[project]
name = "geolocator"
version = "0.1.0"
description = "Image-based geolocation predictor"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow",
    "exifread",
    "tensorflow",
    "tensorflow-metal",
    "transformers",
    "requests",
    "typer",
    "rich"
]
